language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - SAMP_SERVER_ROOT=$TRAVIS_BUILD_DIR/samp03

install:
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib cmake python python-pip

  - wget https://github.com/Zeex/pawn/releases/download/20150412/pawnc-3.10.20150412-linux.tar.gz
  - sudo tar xvf pawnc-3.10.20150412-linux.tar.gz --strip-components=1 -C /usr/local
  - sudo ldconfig

  - wget https://www.dropbox.com/s/c6pu3qolxqeb480/samp03zsvr_R4.tar.gz
  - tar xvf samp03zsvr_R4.tar.gz

  - wget https://www.dropbox.com/s/9b5wca29x8uc9yi/samp03z_svr_R4_win32.zip
  - unzip samp03z_svr_R4_win32.zip -d $SAMP_SERVER_ROOT pawno/include/*

  - sudo pip install samp-server-cli

before_script:
  - cmake . -DCMAKE_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}

script:
  - make
  - make test
  - make package

after_failure:
  - cat Testing/Temporary/LastTest.log

deploy:
  provider: releases
  api_key:
    secure: Z3wKluTQv4AT61kbY1Dql0cf3Jic1vfuPcuPLcktC45Y3+O40GaDnM/3k9zkhYMwTBCzery2YUGMXcaQO7EahgrDwjXlJ+owC+XD0NOpwIw7zzwyQd+M77s4djHhamSeKX5pqqPgjA0VBa9Q/uIjpY3lpLQ2xcsojRB8PoYWTyw=
  file_glob: true
  file:
    - 'jit-*-linux.tar.gz'
  draft: true
  skip_cleanup: true
  on:
    repo: Zeex/samp-plugin-jit
    tags: true
    condition: "$CC = gcc"
