language: cpp
compiler:
  - gcc
env:
  global:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/samp-server-cli/bin
    - SAMP_SERVER_ROOT=$TRAVIS_BUILD_DIR/samp03
    - SAMP_SERVER=$TRAVIS_BUILD_DIR/samp03/samp03svr
    - CTEST_OUTPUT_ON_FAILURE=TRUE
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib cmake python
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.sh
  - sudo sh cmake-2.8.12.2-Linux-i386.sh --exclude-subdir --prefix=/usr
  - git clone --depth 1 https://github.com/Zeex/samp-server-cli.git
  - wget http://files.sa-mp.com/samp03zsvr_R4.tar.gz
  - tar xvf samp03zsvr_R4.tar.gz
before_script:
  - cmake . -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
script:
  - make
  - make test
  - make package
