version: '{build}'

configuration:
  - RelWithDebInfo

install:
  - appveyor DownloadFile https://github.com/Zeex/pawn/releases/download/pawncc-20141116/pawncc-win32.zip
  - 7z x pawncc-win32.zip -opawn
  - set PATH=%PATH%;%CD%\pawn

  - appveyor DownloadFile https://www.dropbox.com/s/9b5wca29x8uc9yi/samp03z_svr_R4_win32.zip?dl=1
  - 7z x samp03z_svr_R4_win32.zip -oserver
  - set SAMP_SERVER_ROOT=%CD%\server

  - git clone --depth 1 https://github.com/Zeex/samp-server-cli.git server\cli
  - set PATH=%PATH%;%CD%\server\cli

before_build:
  - cmake . -G "Visual Studio 10 2010"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

test_script:
  - ctest --build-config %CONFIGURATION%

artifacts:
  - path: jit-*-win32.zip
    name: Binaries

on_failure:
  - type Testing\Temporary\LastTest.log
